"""LFS assets and every file above 5 MB; remaining small legacy blobs stay in Git."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE = "tools/assets/lfs_legacy_blobs.json"
LFS_SUFFIXES = {".blend", ".blend1", ".glb", ".obj"}
SIZE_LIMIT = 5_000_000
LFS_ATTRIBUTES = "filter=lfs diff=lfs merge=lfs -text"


def git(root: Path, *args: str, input: str | None = None) -> str:
    return subprocess.check_output(["git", "-C", str(root), *args], input=input, text=True)


def candidate_paths(root: Path) -> list[str]:
    paths = git(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z")
    return sorted({p for p in paths.split("\0") if p and (root / p).is_file()})


def path_pattern(path: str) -> str:
    # C quoting handles spaces and non-ASCII names; escape glob metacharacters
    # because a generated entry names one file, rather than a family of assets.
    escaped = "".join("\\" + c if c in "*?[]" else c for c in path)
    return json.dumps("/" + escaped, ensure_ascii=False)


def policy(root: Path) -> tuple[str, set[str], list[str]]:
    baseline = json.loads((root / BASELINE).read_text(encoding="utf-8"))["files"]
    paths = candidate_paths(root)
    existing = [p for p in paths if p in baseline]
    hashes = git(root, "hash-object", "--no-filters", "--stdin-paths",
                 input="".join(json.dumps(p, ensure_ascii=False) + "\n" for p in existing)).splitlines()
    unchanged = {p for p, oid in zip(existing, hashes) if oid == baseline[p]}
    large_files = {p for p in paths if (root / p).stat().st_size > SIZE_LIMIT}
    required = {p for p in paths if Path(p).suffix.lower() in LFS_SUFFIXES or p in large_files}
    required -= unchanged
    lines = ["# Generated by python3 tools/assets/sync_lfs_attributes.py; do not edit.",
             "# Remaining small legacy assets retain their ordinary Git blobs after history migration."]
    lines.extend(f"*{suffix} {LFS_ATTRIBUTES}" for suffix in sorted(LFS_SUFFIXES))
    mixed_case = {p for p in required if Path(p).suffix.lower() in LFS_SUFFIXES
                  and Path(p).suffix != Path(p).suffix.lower()}
    if mixed_case:
        lines.append("\n# Asset suffixes with non-lowercase spelling, registered by exact path.")
        lines.extend(f"{path_pattern(p)} {LFS_ATTRIBUTES}" for p in sorted(mixed_case))
    lines.append("\n# Files larger than 5,000,000 bytes, registered by exact path.")
    lines.extend(f"{path_pattern(p)} {LFS_ATTRIBUTES}" for p in sorted(large_files - unchanged))
    lines.append("\n# Unchanged ordinary blobs from the adoption baseline.")
    lines.extend(f"{path_pattern(p)} -filter -diff -merge -text" for p in sorted(unchanged))
    return "\n".join(lines) + "\n", required, paths
